### ISSUE TITLE
implement local db / metfrag as conditional

### ISSUE THREAD

**Issue by bernt-matthias** [computational-metabolomics/metfrag-galaxy#5]
Since either a local db or a metfrag db has to be chosen this shoud be realised with a conditional.

**Comment by korseby** [comment]
For that you need a local db running. We should have a Dockerfile floating around somewhere here https://github.com/ipb-halle/MetFragRelaunched/tree/containerize

I think we should implement this in the rewrite of the tool

**Comment by korseby** [comment]
The Dockerfile and instructions to build the local pubchem mirror database can be found here: https://github.com/c-ruttkies/container-metchemdata

@sneumann also has recent kubernetes deployment yamls.

**Comment by Tomnl** [comment]
@RJMW  we can set this local database system up on one of the Birmingham virtual machines

**Comment by bernt-matthias** [comment]
Currently in the tool the "local data base" is just a csv file. 

Most frequently the Galaxy tool-data loc files specify files, but its definitely possible to specify a connection string. 

For my curiosity: the DB you are referring to is some SQL DB? In the docker it seems to be postgres in the backend, but could be any DB (sqlite)?

**Comment by Tomnl** [comment]
hi @bernt-matthias,

We should still keep the option to have  a "local database" that is just a csv file, and it should be realised as a conditional - like you mentioned in the original issue message.

The database @korseby is referring to is a local PubChem database (With a few modifications - called MetChem) and can be used in replace of doing the API calls to the public PubChem instance. See [xml](https://github.com/korseby/container-msnbase/blob/develop/galaxy/msp-to-metfrag.xml#L78) and [script](https://github.com/korseby/container-msnbase/blob/develop/scripts/msp-to-metfrag.r#L702).  

So, I will update Galaxy tool and script here for the following database options:

- PubChem
- KEGG
- ChemSpider - if still working
- MetChem 
  - (and provide option for user to choose IP address of local instance)
- LocalCSV 
  - (and provide option for user to choose an uploaded CSV file)

@RJMW

**Comment by RJMW** [comment]
I agree @Tomnl.

Examples for "LocalCSV" are available from here:
https://msbi.ipb-halle.de/~cruttkie/databases/
https://msbi.ipb-halle.de/~cruttkie/metfrag/example_local_inchi_file.txt

@korseby are there any more up-to-date csv files available?

**Comment by Tomnl** [comment]
This is now implemented following #8
