### ISSUE TITLE
Update based on the msp-to-metfrag PhenoMenal tool

### ISSUE THREAD

**Issue by Tomnl** [computational-metabolomics/metfrag-galaxy#6]
After some discussion with @korseby we are going to update the galaxy tool here (https://github.com/computational-metabolomics/metfrag-galaxy) with the functionality that has been developed as part of PhenoMenal  ([script](https://github.com/korseby/container-msnbase/blob/develop/scripts/msp-to-metfrag.r) and [xml](https://github.com/korseby/container-msnbase/blob/develop/galaxy/msp-to-metfrag.xml)). Keeping the tool as python though.

The plan will be that we will later migrate this tool to a central Metfrag repository

@jsaintvanne: What is the status with your pull requests? Can you update or create a new pull request that merges them with the branch "phen_msp_to_metrag_update". 

FYI: @RJMW

**Comment by jsaintvanne** [comment]
Hi,
Sounds good that we can interact with PhenoMenal team for that !

I'm sorry but I don't really understand what you mean ? Do you want that I recreate my PR directly on the new branch ?
I'm actually searching why Travis tests are not good with my updates because I don't really change the base script, just add some filters...

@lecorguille @yguitton

**Comment by Tomnl** [comment]
> Do you want that I recreate my PR directly on the new branch ?

Yes please. Although if you can fix the travis tests we can just merge straight to the the master branch.

**Comment by jsaintvanne** [comment]
> Yes please. Although if you can fix the travis tests we can just merge straight to the the master branch.

Ok, I now know why the Travis test is not good. It is because the input.msp file is not the same format as the output of something extract from msPurity...
Should I change it ?
